version: '3.3'

services:
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_test_2
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8081:8081'
    volumes:
      - ./app:/var/www/symfony_test_2
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
